import { EXCERPT } from "./excerpt.js";

export const BIBLESET = [ 
  EXCERPT.PRAISE, 
  EXCERPT.DEVOTION, 
  EXCERPT.DOUBT,
  EXCERPT.GRUDGE, 
  EXCERPT.DESPAIR, 
  EXCERPT.TRIAL, 
  EXCERPT.PERSECUTION, 
  EXCERPT.JEWS, 
  EXCERPT.GENTILES, 
  EXCERPT.SCEPTICS
];