
export const EXCERPT = Object.freeze({
  PRAISE: 'PRAISE',
  DEVOTION: 'DEVOTION',
  DOUBT: 'DOUBT',
  GRUDGE: 'GRUDGE',
  DESPAIR: 'DESPAIR',
  TRIAL: 'TRIAL',
  PERSECUTION: 'PERSECUTION',
  JEWS: 'JEWS',
  GENTILES: 'GENTILES',
  SCEPTICS: 'SCEPTICS',
  SHABBAT: 'SHABBAT'
});